title: "Federico"
description: "Federico's Blog ~ Technical posts"
# google_analytics: UA-XXXXXXXXX-X

# Build settings
permalink: /:categories/:title.html
markdown: kramdown
github: [metadata]
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - 'README.md'
plugins:
  - jekyll-feed
  - github-pages
  - jekyll-diagrams

defaults:
  - scope:
      path: _posts
    values:
      layout: post
      author: Federico

#bio info
name: "Federico"
what_do_as: "Cyber Security"
live: "London"
